spring.mail.host=${MAILHOST}
spring.mail.port=${MAILPORT}
spring.mail.username=${USERNAME}
spring.mail.password=${PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
server.port=443
